### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by siyuanchen2020** [MasterYip/ChatPaper2Xmind#13]
我运行代码的时候反复出现这个错误：
Traceback (most recent call last):
  File "paper2xmind.py", line 5, in <module>
    from pdf_parser import PDFFigure2PaperParser, PDFPaperParser
  File "C:\Users\HY\Python Code\ChatPaper2XMind\pdf_parser.py", line 4, in <module>
    from pdf_extract import *
  File "C:\Users\HY\Python Code\ChatPaper2XMind\pdf_extract\__init__.py", line 362, in <module>
    def getDensityMap(BoxWeightList, roi: tuple[4],
TypeError: 'type' object is not subscriptable

请问这个需要怎么调整呢？感谢！

**Comment by MasterYip** [comment]
请使用3.8（好像）或以上版本
