### ISSUE TITLE
PDFFigure2PaperParser' object has no attribute 'pdf

### ISSUE THREAD

**Issue by WeiningKan** [MasterYip/ChatPaper2Xmind#18]
C:\Users\weini\ChatPaper2Xmind>python paper2xmind.py --path "E:\Paper\GEOThought\fis"
E:\Paper\GEOThought\fis\fish.pdf
Traceback (most recent call last):
  File "C:\Users\weini\ChatPaper2Xmind\paper2xmind.py", line 70, in <module>
    pdf_batch_processing(argparser.parse_args().path)
  File "C:\Users\weini\ChatPaper2Xmind\paper2xmind.py", line 46, in pdf_batch_processing
    pdf_processing(pdf_path, xmind_path, usePDFFigure2=usePDFFigure2, debug=debug,
  File "C:\Users\weini\ChatPaper2Xmind\paper2xmind.py", line 17, in pdf_processing
    paper = PDFFigure2PaperParser(pdf_file_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\weini\ChatPaper2Xmind\pdf_parser.py", line 263, in __init__
    self.PDFF2data = parsePDF_PDFFigures2(path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\weini\ChatPaper2Xmind\pdf_extract\__init__.py", line 695, in parsePDF_PDFFigures2
    _ = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function PDFPaperParser.__del__ at 0x000001BB30821C60>
Traceback (most recent call last):
  File "C:\Users\weini\ChatPaper2Xmind\pdf_parser.py", line 31, in __del__
    self.pdf.close()
    ^^^^^^^^
AttributeError: 'PDFFigure2PaperParser' object has no attribute 'pdf'

1. 没有java环境，已改为False
2. 文件dir，全部没有空格，且使用双引号

请帮忙查看问题，感谢

**Comment by MasterYip** [comment]
USE_PDFFIGURE2在paper2xmind文件中被使用。
你的报错信息
File "C:\Users\weini\ChatPaper2Xmind\paper2xmind.py", line 17, in pdf_processing
paper = PDFFigure2PaperParser(pdf_file_path)
表明程序仍然执行了这条语句：

    if usePDFFigure2:
        paper = PDFFigure2PaperParser(pdf_file_path)

请确保USE_PDFFIGURE2变量设置为False。

```python
def pdf_processing(pdf_file_path, xmind_file_path, usePDFFigure2=USE_PDFFIGURE2, debug=DEBUG_MODE,
                   apibase=APIBASE, apikeys=APIKEYS, model=MODEL, keyword=KEYWORD,
                   gpt_enable=GPT_ENABLE, openai_proxy=PROXY, rate_limit=THREAD_RATE_LIMIT,
                   fake_response=FAKE_GPT_RESPONSE, maxtoken=MAXTOKEN, language=LANGUAGE):
    if usePDFFigure2:
        paper = PDFFigure2PaperParser(pdf_file_path)
    else:
        paper = PDFPaperParser(pdf_file_path)
```

**Comment by WKqq18** [comment]
你好，我后来有更改，但还是没成功。如下：
import os
import argparse
from XmindCopilot import XmindCopilot
from XmindCopilot.XmindCopilot.file_shrink import xmind_shrink
from pdf_parser import PDFFigure2PaperParser, PDFPaperParser
from pdf_extract import *
from xmind_tree import Xmindtree
from config import *
from glob import glob


def pdf_processing(pdf_file_path, xmind_file_path, usePDFFigure2=False, debug=DEBUG_MODE,
                   apibase=APIBASE, apikeys=APIKEYS, model=MODEL, keyword=KEYWORD,
                   gpt_enable=GPT_ENABLE, openai_proxy=PROXY, rate_limit=THREAD_RATE_LIMIT,
                   fake_response=FAKE_GPT_RESPONSE, maxtoken=MAXTOKEN, language=LANGUAGE):
    if usePDFFigure2:
        paper = PDFFigure2PaperParser(pdf_file_path)
    else:
        paper = PDFPaperParser(pdf_file_path)
    if os.path.isfile(xmind_file_path):
        workbook = XmindCopilot.load(xmind_file_path)
    else:
        workbook = XmindCopilot.load(TEMPLATE_XMIND_PATH)
    sheet = workbook.getPrimarySheet()
    root_topic = sheet.getRootTopic()
    paper_topic = root_topic.addSubTopicbyTitle(paper.title[:15])
    tree = Xmindtree(paper_topic, paper, paper.title[:15],
                     apibase=apibase, apikeys=apikeys, model=model, keyword=keyword,
                     gpt_enable=gpt_enable, openai_proxy=openai_proxy, rate_limit=rate_limit,
                     fake_response=fake_response, maxtoken=maxtoken, language=language)
    tree.gen_summary(verbose=debug)
    tree.save_xmind(xmind_file_path)
    if debug:
        paper.save_pdf(debug=True)


def pdf_batch_processing(path, usePDFFigure2=USE_PDFFIGURE2, debug=DEBUG_MODE,
                         apibase=APIBASE, apikeys=APIKEYS, model=MODEL, keyword=KEYWORD,
                         gpt_enable=GPT_ENABLE, openai_proxy=PROXY, rate_limit=THREAD_RATE_LIMIT,
                         fake_response=FAKE_GPT_RESPONSE, maxtoken=MAXTOKEN, language=LANGUAGE):
    if os.path.isdir(path):
        xmind_path = os.path.join(path, "summary.xmind")
        for pdf_path in glob(os.path.join(path, '**/*.pdf'), recursive=True):
            if pdf_path.endswith('.pdf') and not pdf_path.endswith('_debug.pdf'):
                print("\033[92m" + pdf_path)
                pdf_processing(pdf_path, xmind_path, usePDFFigure2=usePDFFigure2, debug=debug,
                               apibase=apibase, apikeys=apikeys, model=model, keyword=keyword,
                               gpt_enable=gpt_enable, openai_proxy=openai_proxy, rate_limit=rate_limit,
                               fake_response=fake_response, maxtoken=maxtoken, language=language)
        print("\033[95mXmind size shrinking...")
        xmind_shrink(xmind_path)
    elif os.path.isfile(path) and path.endswith('.pdf'):
        pdf_path = path
        xmind_path = os.path.splitext(pdf_path)[0] + ".xmind"
        pdf_processing(pdf_path, xmind_path, usePDFFigure2=usePDFFigure2, debug=debug,
                       apibase=apibase, apikeys=apikeys, model=model, keyword=keyword,
                       gpt_enable=gpt_enable, openai_proxy=openai_proxy, rate_limit=rate_limit)
        print("\033[95mXmind size shrinking...")
        xmind_shrink(xmind_path)
    else:
        print(
            "\033[91m" + "Invalid path! Please input a pdf file or a folder containing pdf files.")
        return


if __name__ == "__main__":
    argparser = argparse.ArgumentParser()
    argparser.add_argument("--path", type=str, default=r'./PDFexample',
                           help="Pdf file or a folder containing pdf files.")
    pdf_batch_processing(argparser.parse_args().path)

**Comment by WKqq18** [comment]
```
import os
import argparse
from XmindCopilot import XmindCopilot
from XmindCopilot.XmindCopilot.file_shrink import xmind_shrink
from pdf_parser import PDFFigure2PaperParser, PDFPaperParser
from pdf_extract import *
from xmind_tree import Xmindtree
from config import *
from glob import glob


def pdf_processing(pdf_file_path, xmind_file_path, usePDFFigure2=False, debug=DEBUG_MODE,
                   apibase=APIBASE, apikeys=APIKEYS, model=MODEL, keyword=KEYWORD,
                   gpt_enable=GPT_ENABLE, openai_proxy=PROXY, rate_limit=THREAD_RATE_LIMIT,
                   fake_response=FAKE_GPT_RESPONSE, maxtoken=MAXTOKEN, language=LANGUAGE):
    if usePDFFigure2:
        paper = PDFFigure2PaperParser(pdf_file_path)
    else:
        paper = PDFPaperParser(pdf_file_path)
    if os.path.isfile(xmind_file_path):
        workbook = XmindCopilot.load(xmind_file_path)
    else:
        workbook = XmindCopilot.load(TEMPLATE_XMIND_PATH)
    sheet = workbook.getPrimarySheet()
    root_topic = sheet.getRootTopic()
    paper_topic = root_topic.addSubTopicbyTitle(paper.title[:15])
    tree = Xmindtree(paper_topic, paper, paper.title[:15],
                     apibase=apibase, apikeys=apikeys, model=model, keyword=keyword,
                     gpt_enable=gpt_enable, openai_proxy=openai_proxy, rate_limit=rate_limit,
                     fake_response=fake_response, maxtoken=maxtoken, language=language)
    tree.gen_summary(verbose=debug)
    tree.save_xmind(xmind_file_path)
    if debug:
        paper.save_pdf(debug=True)


def pdf_batch_processing(path, usePDFFigure2=USE_PDFFIGURE2, debug=DEBUG_MODE,
                         apibase=APIBASE, apikeys=APIKEYS, model=MODEL, keyword=KEYWORD,
                         gpt_enable=GPT_ENABLE, openai_proxy=PROXY, rate_limit=THREAD_RATE_LIMIT,
                         fake_response=FAKE_GPT_RESPONSE, maxtoken=MAXTOKEN, language=LANGUAGE):
    if os.path.isdir(path):
        xmind_path = os.path.join(path, "summary.xmind")
        for pdf_path in glob(os.path.join(path, '**/*.pdf'), recursive=True):
            if pdf_path.endswith('.pdf') and not pdf_path.endswith('_debug.pdf'):
                print("\033[92m" + pdf_path)
                pdf_processing(pdf_path, xmind_path, usePDFFigure2=usePDFFigure2, debug=debug,
                               apibase=apibase, apikeys=apikeys, model=model, keyword=keyword,
                               gpt_enable=gpt_enable, openai_proxy=openai_proxy, rate_limit=rate_limit,
                               fake_response=fake_response, maxtoken=maxtoken, language=language)
        print("\033[95mXmind size shrinking...")
        xmind_shrink(xmind_path)
    elif os.path.isfile(path) and path.endswith('.pdf'):
        pdf_path = path
        xmind_path = os.path.splitext(pdf_path)[0] + ".xmind"
        pdf_processing(pdf_path, xmind_path, usePDFFigure2=usePDFFigure2, debug=debug,
                       apibase=apibase, apikeys=apikeys, model=model, keyword=keyword,
                       gpt_enable=gpt_enable, openai_proxy=openai_proxy, rate_limit=rate_limit)
        print("\033[95mXmind size shrinking...")
        xmind_shrink(xmind_path)
    else:
        print(
            "\033[91m" + "Invalid path! Please input a pdf file or a folder containing pdf files.")
        return


if __name__ == "__main__":
    argparser = argparse.ArgumentParser()
    argparser.add_argument("--path", type=str, default=r'./PDFexample',
                           help="Pdf file or a folder containing pdf files.")
    pdf_batch_processing(argparser.parse_args().path)

```
