### ISSUE TITLE
 AttributeError: 'OutputRedirectThread' object has no attribute 'flush'

### ISSUE THREAD

**Issue by ThomasXIONG151215** [MasterYip/ChatPaper2Xmind#22]
windows11 电脑下下载alpha版，proxy地址http:\\127.0.0.1不知道有没有填错
程序本身在g盘，pdf文件在c盘Downloads

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\ChatPaper2Xmind.int", line 191, in generate_xmind_thread
    pdf_batch_processing(self.lineEdit_PATH.text(), usePDFFigure2=self.config['USE_PDFFIGURE2'],
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\paper2xmind.py", line 55, in pdf_batch_processing
    pdf_processing(pdf_path, xmind_path, usePDFFigure2=usePDFFigure2, debug=debug,
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\paper2xmind.py", line 17, in pdf_processing
    paper = PDFFigure2PaperParser(pdf_file_path)
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\pdf_parser.py", line 264, in __init__
    super().__init__(path, title, url, authors)
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\pdf_parser.py", line 24, in __init__
    self.abstract = self.get_abstract()
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\pdf_parser.py", line 298, in get_abstract
    return self.PDFF2data.get('abstractText').get('text')
AttributeError: 'NoneType' object has no attribute 'get'
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-1, started 63576)>>
Traceback (most recent call last):
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 934, in _bootstrap_inner
  File "threading.py", line 1212, in invoke_excepthook
AttributeError: 'OutputRedirectThread' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'OutputRedirectThread' object has no attribute 'flush'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\ChatPaper2Xmind.int", line 191, in generate_xmind_thread
    pdf_batch_processing(self.lineEdit_PATH.text(), usePDFFigure2=self.config['USE_PDFFIGURE2'],
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\paper2xmind.py", line 55, in pdf_batch_processing
    pdf_processing(pdf_path, xmind_path, usePDFFigure2=usePDFFigure2, debug=debug,
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\paper2xmind.py", line 17, in pdf_processing
    paper = PDFFigure2PaperParser(pdf_file_path)
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\pdf_parser.py", line 264, in __init__
    super().__init__(path, title, url, authors)
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\pdf_parser.py", line 24, in __init__
    self.abstract = self.get_abstract()
  File "G:\LLM\ChatPaper2Xmind-x64-v1.0.0-alpha\pdf_parser.py", line 298, in get_abstract
    return self.PDFF2data.get('abstractText').get('text')
AttributeError: 'NoneType' object has no attribute 'get'
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-4, started 76212)>>
Traceback (most recent call last):
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 934, in _bootstrap_inner
  File "threading.py", line 1212, in invoke_excepthook
AttributeError: 'OutputRedirectThread' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'OutputRedirectThread' object has no attribute 'flush'

**Comment by MasterYip** [comment]
把USE PDFFIGURE2关了试试
我发现他经常没有返回值
