### ISSUE TITLE
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by RosettaYui** [MasterYip/ChatPaper2Xmind#24]
作者您好，我在使用中遇到问题，似乎在缩减大小时报错，这个问题怎么解决呢？

Images Generating...
Xmind size shrinking...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "C:\Users\Yui Rosetta\Desktop\ChatPaper2Xmind-x64-v1.0.0-alpha\ChatPaper2Xmind.int", line 191, in generate_xmind_thread
    pdf_batch_processing(self.lineEdit_PATH.text(), usePDFFigure2=self.config['USE_PDFFIGURE2'],
  File "C:\Users\Yui Rosetta\Desktop\ChatPaper2Xmind-x64-v1.0.0-alpha\paper2xmind.py", line 59, in pdf_batch_processing
    xmind_shrink(xmind_path)
  File "C:\Users\Yui Rosetta\Desktop\ChatPaper2Xmind-x64-v1.0.0-alpha\XmindCopilot\XmindCopilot\file_shrink\__init__.py", line 147, in xmind_shrink
    shrink_images(os.path.join(TMP_DIR, "attachments"),
  File "C:\Users\Yui Rosetta\Desktop\ChatPaper2Xmind-x64-v1.0.0-alpha\XmindCopilot\XmindCopilot\file_shrink\__init__.py", line 63, in shrink_images
    pngquant_compress(folder_path, force=True, quality=PNG_Quality)
  File "C:\Users\Yui Rosetta\Desktop\ChatPaper2Xmind-x64-v1.0.0-alpha\XmindCopilot\XmindCopilot\file_shrink\__init__.py", line 50, in pngquant_compress
    subprocess.run(command)
  File "subprocess.py", line 493, in run
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-1, started 13892)>>
Traceback (most recent call last):
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 934, in _bootstrap_inner
  File "threading.py", line 1212, in invoke_excepthook
AttributeError: 'OutputRedirectThread' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'OutputRedirectThread' object has no attribute 'flush'

**Comment by RosettaYui** [comment]
> 你可以把缩减大小的代码注释掉，可能你使用的是32位系统。
> （文件应该能够正常生成，不影响使用）

嗯好的，谢谢😊
