### ISSUE TITLE
Win11下的UnicodeDecodeError: 'gbk' codec can't decode byte 错误

### ISSUE THREAD

**Issue by a90091343** [MasterYip/ChatPaper2Xmind#26]
作者你好，我在Win11下运行Alpha程序和命令行程序，都遇到了以下报错：
Traceback (most recent call last):
  File "C:\tmp\ChatPaper2Xmind\paper2xmind.py", line 70, in <module>
    pdf_batch_processing(argparser.parse_args().path)
  File "C:\tmp\ChatPaper2Xmind\paper2xmind.py", line 46, in pdf_batch_processing
    pdf_processing(pdf_path, xmind_path, usePDFFigure2=usePDFFigure2, debug=debug,
  File "C:\tmp\ChatPaper2Xmind\paper2xmind.py", line 17, in pdf_processing
    paper = PDFFigure2PaperParser(pdf_file_path)
  File "C:\tmp\ChatPaper2Xmind\pdf_parser.py", line 263, in __init__
    self.PDFF2data = parsePDF_PDFFigures2(path)
  File "C:\tmp\ChatPaper2Xmind\pdf_extract\__init__.py", line 698, in parsePDF_PDFFigures2
    return json.load(open(op.join(TEMP_DIR, op.basename(pdf_file).replace(".pdf", ".json"))))
  File "C:\Users\111\miniforge3\envs\ChatPaper2Xmind\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 7902: illegal multibyte sequence
Exception ignored in: <function PDFPaperParser.__del__ at 0x0000017DCCEF6F70>

我通过将 `pdf_extract\__init__.py` 中的 `return json.load(open(op.join(TEMP_DIR, op.basename(pdf_file).replace(".pdf", ".json")))`语句加上了 `,encoding='utf-8'` 解决了问题，希望能够帮到你

**Comment by MasterYip** [comment]
感谢反馈！如果你fix了一些小问题欢迎pull request~
